channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bioconductor-outrider=1.24.0
  - bioconda::bioconductor-summarizedexperiment=1.36.0
  - conda-forge::r-base=4.4.3
  - conda-forge::r-dplyr=1.1.4
  - conda-forge::r-ggplot2=3.5.2
  - conda-forge::r-magrittr=2.0.3
  - conda-forge::r-yaml=2.3.10
  - conda-forge::r-data.table=1.17.2
