lint:
  files_exist:
    - .github/workflows/ci.yml
    - tests/default.nf.test
  files_unchanged:
    - .gitignore
  nf_test_content: false
nf_core_version: 3.5.2
repository_type: pipeline
template:
  author: Michaela Mueller, Vicente Yepez, Christian Mertes, Daniela Andrade, Cristian
    Sandu, Andrew Behrens, Julien Gagneur
  description: The detection of RNA Outliers Pipeline (DROP) is an integrative workflow
    to detect aberrant expression, aberrant splicing, and mono-allelic expression
    from raw sequencing files.
  force: false
  is_nfcore: true
  name: drop
  org: nf-core
  outdir: .
  version: 1.0dev
