channels:
  - conda-forge
dependencies:
  - conda-forge::r-base=4.4.3
  - conda-forge::r-data.table=1.17.6
  - conda-forge::r-reshape2
  - conda-forge::r-rcolorbrewer=1.1_3
  - conda-forge::r-ggplot2=3.5.2
  - conda-forge::r-pheatmap
