channels:
- conda-forge
- bioconda
dependencies:
- bioconda::bioconductor-biocparallel=1.40.0
- bioconda::bioconductor-summarizedexperiment=1.36.0
- conda-forge::r-base=4.4.3
- conda-forge::r-data.table=1.17.2
- conda-forge::r-dplyr=1.1.4
