show_navigation: false

custom_content:
  order:
    - sample_count
    - read_counts
    - mapped_vs_counted
    - size_factors
    - reads_statistics
    - meanCounts
    - expressedGenes
    - expressed_genes
    - expression_sex
    - sex_matched

custom_data:
  #────────────────────────────────────────────────────────────────────────────
  # sample_count
  #────────────────────────────────────────────────────────────────────────────
  sample_count:
    section_name: "Number of samples"
    format: "tsv"
    plot_type: "table"
    description: "Total number of local vs. external samples."

  #────────────────────────────────────────────────────────────────────────────
  # Count QC section
  #────────────────────────────────────────────────────────────────────────────
  read_counts:
    section_name: "Count Quality Control - Read Counts"

  mapped_vs_counted:
    section_name: "Count Quality Control - Mapped vs Counted Reads"
    description: |
      Compares total mapped vs counted reads.

      The Mapped vs Counted Reads plot does not include external counts.

      Consider removing samples with too low or too high size factors.

  size_factors:
    section_name: "Count Quality Control - Size Factors"
    description: ""

  reads_statistics:
    section_name: "Reads Summary Statistics"
    format: "tsv"
    plot_type: "table"

  #────────────────────────────────────────────────────────────────────────────
  # filtering
  #────────────────────────────────────────────────────────────────────────────
  meanCounts:
    section_name: "Filtering"
    description: |
      local: A pre-filtered summary of counts using only the local (from BAM) counts. Omitted if no external counts

      all: A pre-filtered summary of counts using only the merged local (from BAM) and external counts

      passed FPKM: Passes the user defined FPKM cutoff in at least 5% of genes

      min 1 read: minimum of 1 read expressed in 5% of genes

      min 10 reads: minimum of 10 reads expressed in 5% of genes

  #────────────────────────────────────────────────────────────────────────────
  # Expressed Genes
  #────────────────────────────────────────────────────────────────────────────
  expressedGenes:
    section_name: "Expressed Genes"

  expressed_genes:
    section_name: "Expressed Genes - table"
    format: "tsv"
    plot_type: "table"

  #────────────────────────────────────────────────────────────────────────────
  # Sample Sex Annotation
  #────────────────────────────────────────────────────────────────────────────
  expression_sex:
    section_name: "Sample Sex Annotation"
    description: "Considerations:The verifying of the samples sex is performed by comparing the expression levels of the genes XIST and UTY. In general, females should have high XIST and low UTY expression, and viceversa for males. For it to work, the sample annotation must have a column called ‘SEX’, with values male/female. If some other values exist, e.g., unknown, they will be matched. The prediction is performed via a linear discriminant analysis on the log2 counts."

  sex_matched:
